apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-scaler-start-config
  
data:
  config.yaml: |
    deployments:
    - namespace: default
      name: web-nginx
      replicas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-scaler-stop-config
  
data:
  config.yaml: |
    deployments:
    - namespace: default
      name: web-nginx
      replicas: 0
