apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-scaler-stop
spec:
  schedule: "55 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: deployment-scaler-service-account
          containers:
          - name: deployment-scaler
            image: deployment-scaler:1.0.0
            volumeMounts:
            - mountPath: /config.yaml
              subPath: config.yaml
              name: config-volume
              readOnly: true
          volumes:
          - name: config-volume
            configMap:
              name: deployment-scaler-stop-config
      backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-scaler-start
spec:
  schedule: "56 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: deployment-scaler-service-account
          containers:
          - name: deployment-scaler
            image: deployment-scaler:1.0.0
            volumeMounts:
            - mountPath: /config.yaml
              subPath: config.yaml
              name: config-volume
              readOnly: true
          volumes:
          - name: config-volume
            configMap:
              name: deployment-scaler-start-config
      backoffLimit: 4
